version: "3" 
services:
  db:
    container_name: servian
    image: postgres:latest
    environment: 
      POSTGRES_DB: "servian"
      POSTGRES_HOST_AUTH_METHOD: "trust"
      DB_USERNAME: postgres 
      DB_PASSWORD: password 
      DB_NAME: servian 
      DB_HOSTNAME: localhost
    restart: always
    ports:
      - 5432:5432    