version: "3" 
services:
  db:
    container_name: servian
    image: postgres:latest
    environment: 
      POSTGRES_DB: "servian"
      POSTGRES_USERNAME: postgres 
      POSTGRES_PASSWORD: password 
      POSTGRES_NAME: servian 
      POSTGRES_HOSTNAME: localhost
    restart: always
    ports:
      - 5432:5432    