version: 2.1
orbs:
  node: circleci/node@1.1.6
commands:
  install_deps:
    steps:
      - run:
          name: Install npm dependencies
          command: |
            npm install


jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - install_deps
      - node/with-cache:
          steps:
            - run: npm test
  unit-test:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - install_deps
      - run: 
          name: run unit-test
          command: |
            npm install mocha 
            npm run test-unit 
  eslint-test:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - install_deps
      - run:
          name: run eslint-test
          command: |
            npm install eslint --save-dev
            npm run test-lint  
           
      
workflows:
    build-and-test:
      jobs:
        - build-and-test
        - unit-test:
            requires:
              - build-and-test
        