version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  # build-and-test:
  #   executor:
  #     name: node/default
  #   steps:
  #     - checkout
  #     - node/with-cache:
  #         steps:
  #           - run: npm install
  #           - run: npm test
  unit-test:
    executor:
      name: node/default
    steps:
      - run: 
          name: unit-test
          command: |
            npm install mocha 
            npm run test-unit 
           
            

 


    

      
workflows:
    build-and-test:
      jobs:
        # - build-and-test
        - unit-test
        # :
        #     requires:
        #       - build-and-test
        